name: CodeCov
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: 'generate report'
      run: |
        pip install coverage
        pip install pytest
        coverage run -m pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: pytestcoverage
        fail_ci_if_error: true